#Numpy

1. What is a Python library? Why do we use Python libraries?

1. A Python library is a collection of pre-written modules or functions that we can use in your Python code. These modules and functions provide ready-made solutions for common tasks, so you don't have to write the code from scratch. Think of it like a toolbox full of tools that you can use to build your programs.

2. Why do we use Python libraries?

- Efficiency: Libraries save you time and effort by providing ready-to-use code for common tasks. Instead of reinventing the wheel, you can leverage existing code to speed up your development process.

- Code Reusability: Libraries promote code reusability, which means you can use the same code in different projects. This reduces redundancy and makes your code more maintainable.

- Modularity: Libraries are organized into modules, making it easy to find and use the specific functions you need. You can import only the modules or functions that are relevant to your task, keeping your code organized.

- Community Support: Popular libraries often have large and active communities of users and developers, which means there's a lot of support available if you need help. You can find documentation, tutorials, and forums where you can ask questions and get assistance.

- Specialized Functionality: Libraries provide access to specialized functionality that you might not be able to easily implement yourself. For example, libraries like NumPy and Pandas offer advanced mathematical and data manipulation capabilities.

2. Examples of Python libraries:

- NumPy: Provides functions for working with numerical data, including arrays, matrices, and mathematical operations.

- Pandas: Provides data structures and functions for data analysis and manipulation, particularly for working with tabular data.

- Matplotlib: Provides functions for creating visualizations, such as plots, charts, and graphs.

- Scikit-learn: Provides tools for machine learning, including algorithms for classification, regression, clustering, and dimensionality reduction.

3. By using these libraries, we can quickly and easily perform complex tasks without having to write a lot of code yourself. This allows you to focus on the specific logic of your program rather than the underlying implementation details.

2. What is the difference between Numpy array and List?

1. NumPy Arrays

- Homogeneous data type: NumPy arrays can only store elements of the same data type. This allows for efficient storage and operations.

- Fixed size: NumPy arrays have a fixed size determined at creation. Changing the size requires creating a new array.

- Element-wise operations: NumPy arrays support element-wise operations, meaning you can perform mathematical operations on entire arrays without looping.
Multidimensional: NumPy arrays can have multiple dimensions, representing matrices or higher-dimensional data structures.

- Efficient memory usage: NumPy arrays store data contiguously in memory, making them more memory-efficient than lists for large datasets.

2. Python Lists

- Heterogeneous data type: Python lists can store elements of different data types, including other lists.

- Dynamic size: Python lists can grow or shrink dynamically as elements are added or removed.
- Element access: Lists are accessed using indexing and slicing, similar to NumPy arrays.
- One-dimensional: Lists are primarily one-dimensional, although they can contain other lists to create nested structures.
- Flexibility: Lists are more flexible for general-purpose data storage and manipulation.

3. When to use which:

- NumPy arrays: Use NumPy arrays for numerical computations, scientific computing, and data analysis where performance and efficiency are crucial.

- Python lists: Use Python lists for general-purpose data storage, tasks involving mixed data types, and scenarios where flexibility is more important than performance.

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [7]:
import numpy as np

l = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

arr = np.array(l)

size = np.size
print(size)

shape = arr.shape
print(shape)

dime = arr.ndim
print(dime)


<function size at 0x7f5b6d999080>
(3, 4)
2


4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [9]:
l2 =[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
arr = np.array(l2)


arr[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [13]:
l2 =[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
arr = np.array(l2)

arr[2,3]


np.int64(12)

6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [14]:
l2 =[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
arr = np.array(l2)

arr[1::2]

array([[5, 6, 7, 8]])

7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [15]:
import random

random_matrix = np.random.rand(3, 3)

print(random_matrix)

[[0.55975906 0.81904357 0.85185056]
 [0.24965595 0.55526617 0.28161983]
 [0.21980425 0.04451588 0.36718508]]


8. Describe the difference between np.random.rand and np.random.randn?

1. np.random.rand

- Generates random numbers from a uniform distribution over the interval [0, 1).
- This means that all values within this interval have an equal probability of being generated.
- The numbers generated are uniformly spread out between 0 and 1.

2. np.random.randn

- Generates random numbers from a standard normal distribution (also known as a Gaussian distribution) with a mean of 0 and a standard deviation of 1.
- This distribution is bell-shaped, with most values clustered around the mean (0) and fewer values further away.
- The numbers generated can be positive or negative and are more likely to be close to 0.

3. In summary:

- np.random.rand: Uniform distribution, values between 0 and 1.
- np.random.randn: Standard normal distribution, values centered around 0.

9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [16]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

new_arr = np.expand_dims(arr, axis=0)  # Add new axis at the beginning (axis=0)
# or
new_arr = np.expand_dims(arr, axis=-1)  # Add new axis at the end (axis=-1)


print("Original array shape:", arr.shape)
print("New array shape:", new_arr.shape)

Original array shape: (3, 4)
New array shape: (3, 4, 1)


10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [17]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Transpose the array
transposed_arr = arr.T  # Using the .T attribute
# or
transposed_arr = np.transpose(arr)  # Using the np.transpose() function

print("Original array:\n", arr)
print("\nTransposed array:\n", transposed_arr)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:

Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python1

 1. Index wise multiplication

 2. Matrix multiplication

 3. Add both the matrics

 4. Subtract matrix B from A

 5. Divide Matrix B by A

In [ ]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 1. Index-wise multiplication
index_wise_mult = A * B
print("Index-wise multiplication:\n", index_wise_mult)

# 2. Matrix multiplication
matrix_mult = A @ B.T  # Need to transpose B for valid matrix multiplication
# or
matrix_mult = np.matmul(A, B.T)  # Alternative way using np.matmul
print("\nMatrix multiplication:\n", matrix_mult)

# 3. Add both matrices
addition = A + B
print("\nAddition:\n", addition)

# 4. Subtract matrix B from A
subtraction = A - B
print("\nSubtraction:\n", subtraction)

# 5. Divide Matrix B by A
division = B / A
print("\nDivision:\n", division)

12. Which function in Numpy can be used to swap the byte order of an array?


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype=np.int32)  # Example array

# Swap byte order in-place
arr.byteswap(inplace=True)

# Or, create a new array with swapped byte order
new_arr = arr.byteswap(inplace=False)

13. What is the significance of the np.linalg.inv function?


1. Solving Linear Equations: The inverse of a matrix is crucial for solving systems of linear equations. If you have an equation of the form Ax = b, where A is a matrix, x is a vector of unknowns, and b is a known vector, you can find the solution for x by calculating the inverse of A and multiplying it with b: x = A⁻¹b.

2. Matrix Operations: The inverse is used in various matrix operations, such as:

a) Calculating the determinant of a matrix.
Finding the eigenvalues and eigenvectors of a matrix.
b) Performing matrix decompositions (e.g., LU decomposition).

3. Linear Transformations: In linear algebra, matrices represent linear transformations. The inverse of a matrix represents the inverse transformation, which undoes the original transformation.

4. Applications: Matrix inverses have numerous applications in various fields, including:

a)Computer graphics: Transforming objects in 3D space.
b)Robotics: Controlling robot movements.
c)Machine learning: Solving optimization problems.
d)Physics: Solving equations of motion.

14. What does the np.reshape function do, and how is it used?


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])  # Original array

# Reshape to a 2x3 array
new_arr = np.reshape(arr, (2, 3))

print("Original array:\n", arr)
print("\nReshaped array:\n", new_arr)

'''
The np.reshape function is used to change the shape of a NumPy array without changing its data.
It gives a new shape to an array without changing its data.
'''


15. What is broadcasting in Numpy?

- Broadcasting is a powerful mechanism in NumPy that allows you to perform arithmetic operations on arrays with different shapes, as long as certain conditions are met. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

1. Shape Compatibility: Broadcasting works by comparing the shapes of the arrays involved in an operation, starting with the trailing dimensions (rightmost) and working backward.

2. Rules for Broadcasting: Two dimensions are compatible if:

They are equal.
One of them is 1.

3. Automatic Expansion: If the dimensions are compatible, NumPy automatically expands the smaller array to match the shape of the larger array by replicating its elements along the necessary dimensions.

4. Element-wise Operation: Once the arrays have compatible shapes, the operation is performed element-wise.
